language = 'C'
name = 'Clang'
version = '19.1.7'
license = [
    { name = 'Apache-2.0', exception = 'LLVM-exception', url = 'https://raw.githubusercontent.com/llvm/llvm-project/main/llvm/LICENSE.TXT' },
]
filename = 'Main.c'

install = '''
cd /tmp/
sudo apt-get install -y software-properties-common
wget https://apt.llvm.org/llvm.sh
sudo bash ./llvm.sh 19
sudo apt-get purge -y --auto-remove software-properties-common
'''

compile = '''
clang-19 -O2 -march=native -std=c23 -Wall -Wextra -DONLINE_JUDGE -DATCODER -lm Main.c
'''

object = 'a.out'

execution = ['./a.out']
